### ISSUE TITLE
TODOs for the final stretch of the Literature Work

### ISSUE THREAD

**Issue by rkrug** [IPBES-Data/IPBES_TCA_Corpus#13]
# TODOs for the final stretch of the Literature Work

 
- [ ] TCA Corpus
    

- [ ] Global results TCA ? (Sebastian) =>  a key message of the assessment for the media “At least x million of initiatives are in place with transformative potential for nature and people”.
	- [ ] Cases (Sebastian, Viki) [https://docs.google.com/document/d/17HFHB01tgXc_HAAoFRR9MbUBeaeHD02epNjc9dYymGw/edit](https://docs.google.com/document/d/17HFHB01tgXc_HAAoFRR9MbUBeaeHD02epNjc9dYymGw/edit) 
	- [x] Arts representation (number OA only) (Sebastian)
	- [x] Media representation (number OA only) (Sebastian)
	- [ ] Possibly Initiatives (percentage and count only) (Sebastian)
	- [ ] Proportion of papers which use elements of imagination to trigger TC
	- [ ] Possibly Initiatives (percentage and count only) (Sebastian)
	- [ ] Proportion of papers which use elements of imagination to trigger TC
		1. [ ] Storytelling, story/ies, narrative
		2. [ ] Drawing (graphics, images, design)
		3. [ ] Art-based (music, song, dance, video, movies, filmmaking, films, theatre)
		4. [ ] Technology (digital drawing, digital art, audio)
		5. [ ] Metaphors
		6. [x] Imagination 
		7. [x] Rights for Nature
		8. [ ] Co-creation, participatory/collaborative processes
 
-  [ ] Ch 5 Strategies and actors
- [ ] Strategies / Options (Sebastian, Viki)
    
-  [ ] Actors to search (Sebastian, Viki)
    

-  [ ] Ch 1
	- [ ] Extract individual corpora (Julia, Ester)
- [ ] Ch 2 
- [x] [Technology](https://docs.google.com/document/d/1_ZtHOwSqsRShDHvvxVSnX_fdx_Fl6Dt4PSx_t84UfMY/edit)
	- [x] Include sentient scores as in the Subsidies (Sebastian)
	- [x] Marine search and graphs and data (Sebastian)
- [ ] Ch 3
	- [ ] Update Approaches separation / Snowball using new lit list [Catherine SABINOT <catherine.sabinot@ird.fr> - Re: IPBES- TC - Chap3 - Last steps with theories and clusters for Rainer analysis](message://%[3c7d189a97-0132-4bb8-907c-1a56f52c502b@ird.fr](mailto:3c7d189a97-0132-4bb8-907c-1a56f52c502b@ird.fr)%3e)(Catherine)
	- [ ] Update Strategies / Options (Viki, Sebastian) [https://docs.google.com/document/d/11rFHdoxMt-CCr2m_XdjIKqwCVzmt-TajKlzIa20Ahtk/edit](https://docs.google.com/document/d/11rFHdoxMt-CCr2m_XdjIKqwCVzmt-TajKlzIa20Ahtk/edit)
	- [ ] 
- [ ] Ch 5 Subsidies
	- [ ] Anything More? (Sebastian, Viki)
